In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv('Census.csv')

In [2]:
 df = df.fillna(0)

In [3]:
df.head()

,Person ID,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,No of hours,Approximated Social Grade
0,7394816,E12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,0.0,4
1,7394832,E12000001,H,3,1,2,1,1,2,1,2,1,1,-9,-9,-9,-9,0.0,-9
2,7394719,E12000001,H,2,1,1,7,2,2,1,1,1,2,5,8,2,-9,0.0,2
3,7394840,E12000001,H,1,1,2,6,4,2,1,3,1,2,5,9,5,-9,0.0,4
4,7394711,E12000001,H,2,1,1,1,1,1,1,1,1,1,-9,-9,-9,-9,0.0,-9

In [4]:
del df['Person ID']

In [5]:
df.head()

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,No of hours,Approximated Social Grade
0,E12000001,H,2,1,2,6,2,2,1,2,1,2,5,8,2,-9,0.0,4
1,E12000001,H,3,1,2,1,1,2,1,2,1,1,-9,-9,-9,-9,0.0,-9
2,E12000001,H,2,1,1,7,2,2,1,1,1,2,5,8,2,-9,0.0,2
3,E12000001,H,1,1,2,6,4,2,1,3,1,2,5,9,5,-9,0.0,4
4,E12000001,H,2,1,1,1,1,1,1,1,1,1,-9,-9,-9,-9,0.0,-9

In [6]:
# Define categorical columns
categorical_columns = ["Region", "Residence Type", "Family Composition", "Population Base", "Age", "Sex", 
                     "Marital Status", "Country of Birth", "Student", "Health", "Ethnic Group", "Religion", 
                     "Economic Activity", "Occupation", "Industry", "Hours worked per week", "Approximated Social Grade"]

# Initialize LabelEncoder
LE = LabelEncoder()

# Apply label encoding to each categorical column
df[categorical_columns] = df[categorical_columns].apply(lambda col: LE.fit_transform(col))

In [7]:
df.head()

,Region,Residence Type,Family Composition,Population Base,Sex,Age,Marital Status,Student,Country of Birth,Health,Ethnic Group,Religion,Economic Activity,Occupation,Industry,Hours worked per week,No of hours,Approximated Social Grade
0,0,1,2,0,1,5,1,1,1,2,1,2,5,8,2,0,0.0,4
1,0,1,3,0,1,0,0,1,1,2,1,1,0,0,0,0,0.0,0
2,0,1,2,0,0,6,1,1,1,1,1,2,5,8,2,0,0.0,2
3,0,1,1,0,1,5,3,1,1,3,1,2,5,9,5,0,0.0,4
4,0,1,2,0,0,0,0,0,1,1,1,1,0,0,0,0,0.0,0

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, mean_absolute_error, mean_squared_error, roc_auc_score,confusion_matrix

# Split the dataset into training and testing sets
X = df.drop("Approximated Social Grade", axis=1)
y = df["Approximated Social Grade"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardize features if necessary
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train and evaluate models using dictionary comprehension
models = {
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Logestic Regression": LogisticRegression()
}
kNN = KNeighborsClassifier(n_neighbors=4)

X_np = np.array(X)
y_np = np.array(y)

results = {model_name: {
    "Accuracy": accuracy_score(y_test, model.fit(X_train, y_train).predict(X_test)),
    "Precision": precision_score(y_test, model.predict(X_test), average="weighted"),
    "Recall": recall_score(y_test, model.predict(X_test), average="weighted"),
    "F1-score": f1_score(y_test, model.predict(X_test), average="weighted"),
    "Mean Abosolute Error": mean_absolute_error(y_test, model.predict(X_test)),
    "Mean Squared Error": mean_squared_error(y_test, model.predict(X_test)),
    "ROC AUC": roc_auc_score(y_test, model.predict_proba(X_test), multi_class='ovr')  # assuming multi-class problem
} for model_name, model in models.items()}

# Display results
print("Evaluation Results:")
for model_name, metrics in results.items():
    print(f"\n{model_name}:")
    for metric, value in metrics.items():
        print(f"{metric}: {value:.4f}")
        
# Decision Tree
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

print("\nDecision Tree\n")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt), '\n')       

# Random Forest
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("\nRandom Forest\n")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf), '\n')


# Logistic Regression
logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(X_train, y_train)
y_pred_logistic = logistic_model.predict(X_test)

print("\nLogistic Regression\n")
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_logistic), '\n')

/Users/manojkumarmohanta/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Evaluation Results:

Decision Tree:
Accuracy: 0.7891
Precision: 0.7896
Recall: 0.7891
F1-score: 0.7892
Mean Abosolute Error: 0.2800
Mean Squared Error: 0.4428
ROC AUC: 0.8734

Random Forest:
Accuracy: 0.8252
Precision: 0.8254
Recall: 0.8252
F1-score: 0.8251
Mean Abosolute Error: 0.2314
Mean Squared Error: 0.3647
ROC AUC: 0.9648

Logestic Regression:
Accuracy: 0.7044
Precision: 0.7074
Recall: 0.7044
F1-score: 0.6981
Mean Abosolute Error: 0.3937
Mean Squared Error: 0.6187
ROC AUC: 0.9145

Decision Tree

Confusion Matrix:
[[37279     1     7     5     2]
 [    0 17401  5765   685   933]
 [    0  6232 37196  1630  2824]
 [    2   848  1787 16143  5205]
 [    0  1159  3276  5781 26761]]


Random Forest

Confusion Matrix:
[[37294     0     0     0     0]
 [    0 18485  4733   530  1036]
 [    0  4760 38705  1425  2992]
 [    0   610  1309 16621  5445]
 [    0   697  2041  4374 29865]]


Logistic Regression

Confusion Matrix:
[[37294     0     0     0     0]
 [    0 14457  8898    56  1373]
 [    0  8044 33727  1011  5100]
 [    0   324  6372  8680  8609]
 [    0  1090  6359  3286 26242]]

/Users/manojkumarmohanta/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [14]:
# Cross-validation
from sklearn.model_selection import StratifiedKFold,cross_val_score
cv_results = {}
for model_name, model in models.items():
    cv_scores = cross_val_score(model, X, y, cv=StratifiedKFold(n_splits=5), scoring='accuracy')
    cv_results[model_name] = cv_scores
    
# Display cross-validation results
print("\nCross-Validation Results:")
for model_name, scores in cv_results.items():
    print(f"\n{model_name} Cross-Validation Accuracy:")
    print(f"Mean: {scores.mean():.4f}")
    print(f"Standard Deviation: {scores.std():.4f}")

/Users/manojkumarmohanta/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/manojkumarmohanta/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/manojkumarmohanta/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/manojkumarmohanta/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Cross-Validation Results:

Decision Tree Cross-Validation Accuracy:
Mean: 0.6440
Standard Deviation: 0.0243

Random Forest Cross-Validation Accuracy:
Mean: 0.6452
Standard Deviation: 0.0537

Logestic Regression Cross-Validation Accuracy:
Mean: 0.6020
Standard Deviation: 0.0639

/Users/manojkumarmohanta/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(